name: expense_tracker
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  battery_plus: ^6.2.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  flutter:
    sdk: flutter
  flutter_animated_splash: ^0.0.10
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/videos/
    - assets/logos/
    - assets/png/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
